[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["linux-64", "osx-arm64"]
preview = ["pixi-build"]

[dependencies]
"diceart" = { path = "." }

[feature.test.dependencies]
ruff = ">=0.7.4,<0.8"
mypy = ">=1.13.0,<2"
pre-commit = ">=4.0.1,<5"
pytest = ">=8.3.3,<9"
pytest-cov = ">=6.0.0,<7"
[feature.test.pypi-dependencies]
testutils = { path = "tests", editable = true }

[environments]
default = { features = ["test"] }

# see https://github.com/prefix-dev/pixi/issues/2859
[activation.env]
PYTHONNOUSERSITE = "1"

[tasks]
test = "mypy src && pytest tests"
coverage = "pytest --cov=src tests"

[package]
name = "diceart"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies]
hatchling = "==1.26.3"

[package.run-dependencies]
pillow = ">=11.2.1,<12"
numpy = ">=2.2.6,<3"
typer = ">=0.15.4,<0.16"
